// <auto-generated />
namespace PassionProject2024N01604846.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class everything : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(everything));
        
        string IMigrationMetadata.Id
        {
            get { return "202406211803161_everything"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
